server:
  port: 8815 # 服务端口
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    lease-expiration-duration-in-seconds: 90
    lease-renewal-interval-in-seconds: 30
spring:
  cloud:
    config:
      enabled: false
  application:
    name: game-service # 服务名称


spring.rabbitmq.host: 127.0.0.1
spring.rabbitmq.port: 5672
spring.rabbitmq.username: root
spring.rabbitmq.password: root
spring.rabbitmq.virtual-host: sandbox_host

health.config.enabled: false

hystrix.command.default.execution.timeout.enabled: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 30000
hystrix.threadpool.default.coreSize: 30
hystrix.threadpool.default.maximumSize: 80
hystrix.command.default.circuitBreaker.requestVolumeThreshold: 100
hystrix.threadpool.default.allowMaximumSizeToDivergeFromCoreSize: true

ribbon.ReadTimeout: 60000
ribbon.ConnectTimeout: 60000

feign.hystrix.enabled: false

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR


---
spring:
  profiles: test

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://10.0.0.35:8761/eureka/

logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR


