server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000


---
spring:
  profiles: test

eureka:
  instance:
    hostname: peers1
  client:
    serviceUrl:
      defaultZone: http://peers2:${server.port}/eureka/


logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR


---
spring:
  profiles: peers2

eureka:
  instance:
    hostname: peers2
  client:
    serviceUrl:
      defaultZone: http://peers1:${server.port}/eureka/


logging.level.org.springframework.web: ERROR
logging.level.org.hibernate: ERROR


